-- MySQL Script generated by MySQL Workbench
-- Sat Mar  5 02:34:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_PESSOA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_PESSOA` (
  `pk_cpf` VARCHAR(14) NOT NULL,
  `nome_trab` VARCHAR(100) NOT NULL,
  `pis` VARCHAR(11) NULL,
  `ctps_num` VARCHAR(10) NULL,
  `ind_cpf_val` INT(2) NULL,
  `ind_pis_val` INT(2) NULL,
  `data_nasc` DATE NULL,
  `genero` INT(3) NULL,
  `nacionalidad` INT(3) NULL,
  `ano_cheg_pais` DATE NULL,
  `ind_defic` INT(2) NULL,
  `tipo_defic` INT(2) NULL,
  `raca_cor` INT(2) NULL,
  `ind_alv` INT(2) NULL,
  `cbo` INT(10) NULL,
  `fx_etaria` INT(2) NULL,
  `idade` INT(3) NULL,
  `grau_instr` INT(2) NULL,
  PRIMARY KEY (`pk_cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_SETOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_SETOR` (
  `secao_cnae` CHAR(3) NULL,
  `divisao_cnae` VARCHAR(6) NULL,
  `grupo_cnae` VARCHAR(6) NULL,
  `classe_cnae` VARCHAR(8) NULL,
  `pk_setor` VARCHAR(45) NOT NULL,
  `subativ_ibge` INT(10) NULL,
  `subs_ibge` INT(3) NULL,
  PRIMARY KEY (`pk_setor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_LOCAL_EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_LOCAL_EMPRESA` (
  `cod_mun` INT NOT NULL,
  `mun_trab` VARCHAR(45) NULL,
  `regiao_metro` VARCHAR(45) NULL,
  `uf` VARCHAR(2) NULL,
  PRIMARY KEY (`cod_mun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_EMPRESA` (
  `pk_cnpj` INT(14) NOT NULL,
  `id_estab` VARCHAR(8) NOT NULL,
  `razao_social` VARCHAR(45) NOT NULL,
  `cei_vinc` VARCHAR(45) NULL,
  `tipo_estab` VARCHAR(45) NULL,
  `tamestab` VARCHAR(45) NULL,
  `fk_setor` VARCHAR(45) NOT NULL,
  `nat_vinculo` INT(4) NULL,
  `nat_jur` INT(8) NULL,
  `fk_cod_mun` INT NOT NULL,
  PRIMARY KEY (`pk_cnpj`),
  UNIQUE INDEX `id_estab_UNIQUE` (`id_estab` ASC) VISIBLE,
  INDEX `fk_TB_EMPRESA_TB_CNAE1_idx` (`fk_setor` ASC) VISIBLE,
  INDEX `fk_TB_EMPRESA_TB_LOCAL_EMPRESA1_idx` (`fk_cod_mun` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_AFASTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_AFASTAMENTO` (
  `pk_afastamento` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NULL,
  `data_fim` DATE NULL,
  `qt_dias_afast` INT(4) NULL,
  `causa_afast` INT(2) NULL,
  PRIMARY KEY (`pk_afastamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_RESCISAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_RESCISAO` (
  `pk_rescisao` INT NOT NULL AUTO_INCREMENT,
  `data_deslig` VARCHAR(10) NULL,
  `mes_deslig` INT(2) NULL,
  `causa_deslig` INT(3) NULL,
  `causa_resc` INT(1) NULL,
  `vl_resc_banco_horas` VARCHAR(20) NULL,
  `vl_resc_ferias` VARCHAR(20) NULL,
  `vl_resc_gratif` VARCHAR(20) NULL,
  `vl_resc_multa` VARCHAR(20) NULL,
  `vl_resc_reajust_col` VARCHAR(20) NULL,
  `qt_meses_resc_bc_horas` INT(4) NULL,
  `qt_meses_resc_reaj_coletivo` INT(4) NULL,
  PRIMARY KEY (`pk_rescisao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_ADMISSAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_ADMISSAO` (
  `pk_admissao` INT NOT NULL AUTO_INCREMENT,
  `data_adm` DATE NULL,
  `mes_adm` INT(2) NULL,
  `tipo_adm` INT(2) NULL,
  PRIMARY KEY (`pk_admissao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_SINDICATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_SINDICATO` (
  `pk_sind_cnpj` INT(14) NOT NULL,
  `ind_sindc` INT(1) NULL,
  `vl_contr_assist` VARCHAR(20) NULL,
  `vl_contr_assoc1` VARCHAR(20) NULL,
  `vl_contr_assoc2` VARCHAR(20) NULL,
  `vl_contr_confed` VARCHAR(20) NULL,
  `vl_contr_sindic` VARCHAR(20) NULL,
  `cnpj_contr_assist` VARCHAR(20) NULL,
  `cnpj_contr_assoc1` VARCHAR(20) NULL,
  `cnpj_contr_assoc2` VARCHAR(20) NULL,
  `cnpj_contr_confed` VARCHAR(20) NULL,
  PRIMARY KEY (`pk_sind_cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_OUTRAS_REM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_OUTRAS_REM` (
  `pk_outras_rem` INT NOT NULL AUTO_INCREMENT,
  `ind_horas_extras` INT(1) NULL,
  `ind_trab_intermitente` VARCHAR(45) NULL,
  `ind_trab_parcial` VARCHAR(40) NULL,
  `mes_rem_13_adiant` INT(2) NULL,
  `vl_rem_13_adiant` FLOAT NULL,
  `mes_rem_13_final` INT(2) NULL,
  `vl_rem_13_final` FLOAT NULL,
  `rem_dez_r` VARCHAR(20) NULL,
  `rem_dez_sm` VARCHAR(20) NULL,
  `rem_med_r` VARCHAR(20) NULL,
  `rem_med_sm` VARCHAR(20) NULL,
  `vl_ult_rem_ano` VARCHAR(20) NULL,
  PRIMARY KEY (`pk_outras_rem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_REMUNERACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_REMUNERACAO` (
  `pk_remuneracao` INT NOT NULL,
  `fk_outras_rem` INT NOT NULL,
  `vl_rem` VARCHAR(20) NULL,
  `mes_rem` INT(2) NULL,
  `ano_rem` INT(4) NULL,
  `qt_horas_extras` INT(3) NULL,
  PRIMARY KEY (`fk_outras_rem`, `pk_remuneracao`),
  INDEX `fk_TB_REMUNERACAO_TB_OUTRAS_REMU1_idx` (`fk_outras_rem` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_VINCULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_VINCULO` (
  `fk_cpf` VARCHAR(12) NOT NULL,
  `fk_cnpj` INT NOT NULL,
  `emp_31dez` INT(2) NULL,
  `fk_afastamento` INT NOT NULL,
  `horas_cont` INT(3) NULL,
  `peso` VARCHAR(10) NULL,
  `sit_vinculo` INT(10) NULL,
  `temp_empr` VARCHAR(10) NULL,
  `tipo_vinculo` INT(4) NULL,
  `fk_demissao` INT NOT NULL,
  `fk_admissao` INT NOT NULL,
  `fk_sind_cnpj` INT(14) NOT NULL,
  `salario` VARCHAR(20) NULL,
  `tipo_salario` VARCHAR(1) NULL,
  `fk_outras_rem` INT NOT NULL,
  `fk_remuneracao` INT NOT NULL,
  PRIMARY KEY (`fk_cpf`, `fk_cnpj`, `fk_afastamento`, `fk_demissao`, `fk_admissao`, `fk_sind_cnpj`, `fk_outras_rem`, `fk_remuneracao`),
  INDEX `fk_TB_PESSOA_has_TB_EMPRESA_TB_EMPRESA1_idx` (`fk_cnpj` ASC) VISIBLE,
  INDEX `fk_TB_PESSOA_has_TB_EMPRESA_TB_PESSOA_idx` (`fk_cpf` ASC) VISIBLE,
  INDEX `fk_TB_VINCULO_TB_AFASTAMENTO1_idx` (`fk_afastamento` ASC) VISIBLE,
  INDEX `fk_TB_VINCULO_TB_RESCISAO1_idx` (`fk_demissao` ASC) VISIBLE,
  INDEX `fk_TB_VINCULO_TB_ADMISSAO1_idx` (`fk_admissao` ASC) VISIBLE,
  INDEX `fk_TB_VINCULO_TB_SINDICATO1_idx` (`fk_sind_cnpj` ASC) VISIBLE,
  INDEX `fk_TB_VINCULO_TB_REMUNERACAO1_idx` (`fk_outras_rem` ASC, `fk_remuneracao` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
